[config]
name: "template" # 游戏名称
platform: "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path: "C:\Games" # 游戏路径
exe_path: "template.exe" # 运行文件相对路径
save_path: "template\saves\" # 存档文件相对路径

[download]
url: "steam" # steam，或下载地址/页面
