[game]
name = "Dyson Sphere Program" # 游戏名称
name-zh-cn = "戴森球计划" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = 'unknown' # 游戏路径
exe_path = 'unknown' # 运行文件相对路径
save_path = 'D:\Files\Documents\Dyson Sphere Program\Save' # 存档文件相对路径
save_latest = false # 是否只保存save_path下最新创建的文件夹，用于游戏存档只增不减的情况
is_folder = true # 目标是否是文件夹，不然是单文件，只在save_latest为true时生效
need_zip = false # 是否需要压缩

[base]
download = "steam" # steam，或下载地址/页面
