[game]
name = "Tiny Tina's Wonderlands" # 游戏名称
name-zh-cn = "小缇娜的奇幻冒险" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = '' # 游戏路径
exe_path = '' # 运行文件相对路径
save_path = "D:/Files/Documents/My Games/Tiny Tina's Wonderlands/Saved/SaveGames/76561198876586946" # 存档文件相对路径
save_latest = false

[base]
download = "steam" # steam，或下载地址/页面
