[game]
name = "Terraria" # 游戏名称
name-zh-cn = "泰拉瑞亚" # 游戏名称中文
platform = "win10" # 运行平台：win10 linux mac android ios win7 winxp ns
path = 'C:\Apps\Steam\steamapps\common\Terraria' # 游戏路径
exe_path = 'C:\Apps\Steam\steamapps\common\Terraria\Terraria.exe' # 运行文件相对路径
save_path = 'D:\Files\Documents\My Games\Terraria\Worlds' # 存档文件相对路径
save_latest = false

[base]
download = "steam" # steam，或下载地址/页面
